version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - HELIUS_API_KEY=${HELIUS_API_KEY:-acaa0918-3e51-400c-a8e9-a497fee3a8e1}
      - REDIS_URL=redis://redis:6379
    depends_on:
      - redis
    volumes:
      - ./src:/app/src

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: 